export const USER_NICKNAME_DEFINED ="USER_NICKNAME_DEFINED"
export const USER_PASSWORD_DEFINED ="USER_PASSWORD_DEFINED";
export const USER_ASSIGNED ="USER_ASSIGNED";
export const USERS_POSTS_FETCHED = "USERS_POSTS_FETCHED";
export const USERS_FEEDS_FETCHED ="USERS_FEEDS_FETCHED";
export const NEW_POST_CREATED ="NEW_POST_CREATED";
export const POST_UPDATED = "POST_UPDATED";
export const POST_DELETED ="POST_DELETED"